import { Platform } from 'react-native';

export const Colors = {
  light: {
    primary: '#10B981',
    primaryDark: '#059669',
    primaryLight: '#D1FAE5',
    background: '#FFFFFF',
    surface: '#FFFFFF',
    surfaceSoft: '#F3F4F6',
    border: '#E5E7EB',
    text: '#000000',
    secondaryText: '#6B7280',
    success: '#22C55E',
    warning: '#F59E0B',
    danger: '#EF4444',
    blue: '#3B82F6',
    orange: '#F97316',
    tint: '#10B981',
    icon: '#6B7280',
    tabIconDefault: '#6B7280',
    tabIconSelected: '#10B981',
  },
  dark: {
    primary: '#10B981',
    primaryDark: '#059669',
    primaryLight: '#064E3B',
    background: '#000000',
    surface: '#111111',
    surfaceSoft: '#1A1A1A',
    border: '#262626',
    text: '#FFFFFF',
    secondaryText: '#9CA3AF',
    success: '#22C55E',
    warning: '#F59E0B',
    danger: '#EF4444',
    blue: '#3B82F6',
    orange: '#F97316',
    tint: '#10B981',
    icon: '#9CA3AF',
    tabIconDefault: '#9CA3AF',
    tabIconSelected: '#10B981',
  },
};

export const Fonts = Platform.select({
  ios: {
    sans: 'system-ui',
    serif: 'ui-serif',
    rounded: 'ui-rounded',
    mono: 'ui-monospace',
  },
  default: {
    sans: 'normal',
    serif: 'serif',
    rounded: 'normal',
    mono: 'monospace',
  },
  web: {
    sans: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    rounded: "'SF Pro Rounded', 'Hiragino Maru Gothic ProN', Meiryo, 'MS PGothic', sans-serif",
    mono: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
  },
});
